name: Test
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup
      run: make minifab && sudo make minifab-init && make minifab-up

    - name: Test
      run: sudo make testapp && ./minifab apprun
